# Generated by Django 2.2 on 2019-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0002_auto_20190414_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Text', models.TextField()),
                ('Autor', models.CharField(max_length=20)),
                ('CreateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Asks',
            new_name='Ask',
        ),
    ]
