# Generated by Django 2.2 on 2019-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0003_auto_20190414_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=32)),
            ],
        ),
    ]
