# Generated by Django 2.2 on 2019-04-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('asker', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Autor', models.CharField(max_length=32)),
                ('LikeDislikeBalance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('LikeDislikeBalance', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='asker.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='AvatarURL',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Login',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='Autor',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='Title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tag',
            name='TagName',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterModelTable(
            name='question',
            table='Questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asker.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asker.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='asker.Status'),
            preserve_default=False,
        ),
    ]
