# Generated by Django 2.2 on 2019-04-14 18:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('asker', '0005_auto_20190414_1846'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
