# Generated by Django 2.2 on 2019-04-16 07:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('asker', '0007_auto_20190414_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='LikeDislikeBalance',
            new_name='likeDislikeBalance',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='CreateDate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='LikeDislikeBalance',
            new_name='likeDislikeBalance',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='TagName',
            new_name='tagName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='AvatarURL',
            new_name='avatarURL',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Karma',
            new_name='karma',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='NickName',
            new_name='nickName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
