# Generated by Django 2.2 on 2019-04-16 12:04

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('asker', '0009_auto_20190416_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['createDate']},
        ),
    ]
