# Generated by Django 2.2 on 2019-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('asker', '0010_auto_20190416_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
