# Generated by Django 2.2 on 2019-04-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0011_auto_20190416_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='categoryType',
        ),
    ]
