# Generated by Django 2.2 on 2019-04-16 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0012_auto_20190416_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
