# Generated by Django 2.2 on 2019-04-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0013_auto_20190416_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='asker.Status'),
        ),
    ]
