# Generated by Django 2.2 on 2019-04-21 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asker', '0015_auto_20190416_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionDislike',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='QuestionLike',
            new_name='Like',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='user',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='question',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='question',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
        migrations.DeleteModel(
            name='AnswerDislike',
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
    ]
