# Generated by Django 2.2 on 2019-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0018_auto_20190421_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='asker.Tag'),
        ),
    ]
