# Generated by Django 2.2 on 2019-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0020_auto_20190422_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
