# Generated by Django 2.2 on 2019-05-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asker', '0024_auto_20190501_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=(1, 'Like'), verbose_name='is like')),
                ('object_id', models.PositiveIntegerField(default=-1)),
                ('content_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Like author')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answerlikedislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='answerlikedislike',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlikedislike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='questionlikedislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionlikedislike',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionlikedislike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='AnswerLikeDisLike',
        ),
        migrations.DeleteModel(
            name='QuestionLikeDisLike',
        ),
    ]
