# Generated by Django 2.2 on 2019-05-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0025_auto_20190501_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedislike',
            old_name='mark',
            new_name='vote',
        ),
    ]
