# Generated by Django 2.2 on 2019-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0026_auto_20190501_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='karma',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickName',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatarURL',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
