# Generated by Django 2.2 on 2019-05-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0027_auto_20190503_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likeDislikeBalance',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
